server:
  port: 8001


spring:
  application:
    # 会显示在eureka注册服务器列表中的名称
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: q63785095

eureka:
  client:
    # 表示是否将自己注册进EurekaServer   默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息  默认为true
    # 单点无所谓  集群需要设置为true 配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 向哪个eureka服务器注册
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka

mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.nagetive.springcloud.entites
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
