server:
  port: 80

spring:
  application:
    name: cloud-order-service-80


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 向哪个eureka服务器注册
      defaultZone: hhttp://eureka7001:7001/eureka,http://eureka7002:7002/eureka